services:
  traefik:
    image: traefik:v1.7-alpine
    container_name: traefik
    restart: always
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    command: >
      --logLevel='INFO'
      --web
      --InsecureSkipVerify=true
      --defaultentrypoints=https,http
      --entryPoints='Name:http Address::80'
      --entryPoints='Name:https Address::443 TLS Redirect.EntryPoint:http'
      --retry
      --docker
      --docker.endpoint='unix:///var/run/docker.sock'
      --docker.exposedbydefault=true
      --docker.watch=true
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_net

networks:
  docker_net:
    name: docker_net
    driver: bridge
