services:
  bilingual-text-extractor:
    container_name: bilingual-text-extractor
    build:
      dockerfile: Dockerfile
    restart: always
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bilingual-text-extractor.rule=Host(`$HOST`)"
      - "traefik.http.routers.bilingual-text-extractor.entrypoints=websecure"
      - "traefik.http.routers.bilingual-text-extractor.tls=true"
      - "traefik.http.routers.bilingual-text-extractor.tls.certresolver=myresolver"
      - "traefik.http.services.bilingual-text-extractor.loadbalancer.server.port=80"
    volumes:
      - "./app/config/data:/code/app/config/data"
    networks:
      - docker_net
    
networks:
  docker_net:
    name: docker_net
    driver: bridge