version: "3.5"

services:
  bilingual-text-extractor:
    container_name: bilingual-text-extractor
    build:
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bilingual-text-extractor-host1.rule=Host(`$HOST_PRIMARY`)"
      - "traefik.http.routers.bilingual-text-extractor-host1.entrypoints=websecure"
      - "traefik.http.routers.bilingual-text-extractor-host1.tls=true"
      - "traefik.http.routers.bilingual-text-extractor-host1.tls.certresolver=myresolver"
      - "traefik.http.services.bilingual-text-extractor-host1.loadbalancer.server.port=80"
      - "traefik.http.routers.bilingual-text-extractor-host2.rule=Host(`$HOST_SECONDARY`)"
      - "traefik.http.routers.bilingual-text-extractor-host2.entrypoints=websecure"
      - "traefik.http.routers.bilingual-text-extractor-host2.tls=true"
      - "traefik.http.routers.bilingual-text-extractor-host2.tls.certresolver=myresolver"
      - "traefik.http.services.bilingual-text-extractor-host2.loadbalancer.server.port=80"
    volumes:
      - "./app/config/data:/code/app/config/data"
    
networks:
  docker_net:
    name: docker_net