version: "3.5"

services:
  bilingual-text-extractor:
    container_name: bilingual-text-extractor
    build:
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bilingual-text-extractor.rule=Host(`$HOST`)"
      - "traefik.http.routers.bilingual-text-extractor.entrypoints=websecure"
      - "traefik.http.routers.bilingual-text-extractor.tls=true"
      - "traefik.http.routers.bilingual-text-extractor.tls.certresolver=myresolver"
      - "traefik.http.routers.bilingual-text-extractor.middlewares=cors"
      - "traefik.http.services.bilingual-text-extractor.loadbalancer.server.port=80"
      - "traefik.http.routers.bilingual-text-extractor.middlewares=bilingual-header"
      - "traefik.http.middlewares.bilingual-header.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.bilingual-header.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.bilingual-header.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.bilingual-header.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.bilingual-header.headers.addvaryheader=true"
    volumes:
      - "./app/config/data:/code/app/config/data"
    
networks:
  docker_net:
    name: docker_net