services:
  bilingual-text-extractor:
    container_name: bilingual-text-extractor
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - "8090:80"
    networks:
      - docker_net

networks:
  docker_net:
    name: docker_net
    driver: bridge
