services:
  bilingual-text-extractor:
    build:
      dockerfile: Dockerfile.local
      context: .
    env_file:
      - .env.local
    labels:
      - "traefik.api.port=80"
      - "traefik.protocol=http"
      - "traefik.frontend-host1.rule=Host:${HOST}"
    volumes:
      - "./app:/code/app"
    
