version: "3.5"

services:
  bilingual-text-extractor:
    container_name: bilingual-text-extractor
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    ports:
      - "8090:80"
    labels:
      - "traefik.api.port=80"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:${HOST}"
    networks:
      - docker_net

networks:
  docker_net:
    name: docker_net
    driver: bridge
    external: true
